### PR TITLE
Add test helper utility in TypeScript template

### LINKED ISSUE #451: test helper in TS template
Add the `require('fastify-cli/helper')` utility to the TS template.
Now it exports the old interface.

The test was failing during the implementation:

```
templates/app-ts/test/routes/example.test.ts 2> TSError: ⨯ Unable to compile TypeScript:
templates/app-ts/test/routes/example.test.ts 2> templates/app-ts/test/helper.ts(3,23): error TS7016: Could not find a declaration file
for module 'fastify-cli/helper'. '/Users/mspigolon/workspace/fastify-cli/node_modules/fastify-cli/helper.js' implicitly has an 'any'
type.
```

_Originally posted by @Eomm in https://github.com/fastify/fastify-cli/issues/446#issuecomment-1012562061_

### PR DESCRIPTION
**Pull request by nooreldeensalah**
Resolves #451

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nooreldeensalah** [comment]
Seems like CI test is failing on MacOS Node 16, not sure if it's because of this commit or not. I can try to revert it and see

**Comment by nooreldeensalah** [comment]
Seemingly MacOS is failing because of this commit :/, I'll just double-check by dropping the revert commit

**Comment by nooreldeensalah** [comment]
So, I've tried making `--timeout 0` which is equivalent to `--no-timeout` just to see if the test will pass, and it's passing. Not sure if this is a "solution" to these randomly failing tests

**Comment by mcollina** [comment]
Can you increaase the timeout?

**Comment by nooreldeensalah** [comment]
I've increased the timeout for each test in `helper.test.js`, and they are seemingly passing.

Not sure if this is ideal, there are two other possible ways I have in mind:
- `process.TAP_TIMEOUT=<N>`  at the top of the test file (Not sure if this changes it for other tests, don't have sufficient knowledge on this)
- `t.setTimeout(n)` at the top of the test file

**Comment by mcollina** [comment]
I don't understand why don't we bump the timeout we pass via the CLI.

**Comment by nooreldeensalah** [comment]
Ohh, my bad, I thought you meant for this specific test... 😅

I'll pump the global value then

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by nooreldeensalah** [comment]
I just noticed that the merge push CI job failed :/. Even after I increased the CI timeout from `120 seconds` to `300 seconds`.
Even though it pased in the PR CI job. Seems like this is largely non-deterministic. I think maybe you can try increasing the `--timeout` parameter to a larger value, perhaps `1200` seconds (equivalent to 20 minutes), or disable it altogether (but not sure if this is a good idea, because CI might get stuck then).

**Pull request merged**
