### PR TITLE
fix: skip watch test on github ci

### PR DESCRIPTION
**Pull request by simoneb**
Skip one test on GitHub CI. Same tests consistently succeeds locally. It seems other tests have had the same problem over time and are already skipped.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
I think this might be the only sane approach.

**Comment by simoneb** [comment]
> I think this might be the only sane approach.

I tried a few options to no avail, there seems to be a race condition whereby the test directory dynamically created during tests is still locked when tap tries to clean it up.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by simoneb** [comment]
let's retry the build when gh actions recover

**Pull request merged**
