### PR TITLE
Fix-457: TS Testing pattern fix

### PR DESCRIPTION
**Pull request by nnorbert**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by simoneb** [comment]
can you please describe what the PR does and why it works?

**Comment by climba03003** [comment]
It works because the current command is using `shell` glob.
With the quote, it use `glob` package.

This problem is actually depends on system `shell`.
We face the similar problem before in `fastify-swagger` but I forgotten which PR is it.

**Comment by nnorbert** [comment]
The problem was the following, NPM uses **sh** as the shell to run commands which one does not understand the ** glob pattern, it will match only one level. To protect your pattern from being interpreted by sh, simply pass the pattern as a string parameter. If you do so, it will be evaluated by a JavaScript implementation of globs.
Reference: [https://stackoverflow.com/questions/32017169/npm-glob-pattern-not-matching-subdirectories](https://stackoverflow.com/questions/32017169/npm-glob-pattern-not-matching-subdirectories)

**Review by simoneb — APPROVED** [review]

**Comment by simoneb** [comment]
Closes #457

**Pull request merged**
