### PR TITLE
fix: use address 0.0.0.0 in Kubernetes env (#579)

### PR DESCRIPTION
**Pull request by sinedied**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

This PR adds a check so that it automatically use 0.0.0.0 when running inside a Kubernetes environment.

### CODE REVIEW

**Review by climba03003 — COMMENTED** [review]
I still in favor of multiple methods for the detection.

For example, different cloud platform may result in derivation of behavior which means that this environment variables are not always set.
https://stackoverflow.com/questions/66470062/aks-not-creating-kubernetes-service-host-and-kubernetes-service-port-environment

**Comment by climba03003** [comment]
A proper implementation should be follow [`kubectl` check](https://kubernetes.io/docs/reference/kubectl/#in-cluster-authentication-and-namespace-overrides).

> By default kubectl will first determine if it is running within a pod, and thus in a cluster. It starts by checking for the KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT environment variables and the existence of a service account token file at /var/run/secrets/kubernetes.io/serviceaccount/token. If all three are found in-cluster authentication is assumed.

> To maintain backwards compatibility, if the POD_NAMESPACE environment variable is set during in-cluster authentication it will override the default namespace from the service account token. Any manifests or tools relying on namespace defaulting will be affected by this.

We are not authenticating for `in-cluster` but the method is good for environment detection.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by sinedied** [comment]
I'll update the PR based on this

> A proper implementation should be follow [`kubectl` check](https://kubernetes.io/docs/reference/kubectl/#in-cluster-authentication-and-namespace-overrides).
> 
> > By default kubectl will first determine if it is running within a pod, and thus in a cluster. It starts by checking for the KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT environment variables and the existence of a service account token file at /var/run/secrets/kubernetes.io/serviceaccount/token. If all three are found in-cluster authentication is assumed.
> 
> > To maintain backwards compatibility, if the POD_NAMESPACE environment variable is set during in-cluster authentication it will override the default namespace from the service account token. Any manifests or tools relying on namespace defaulting will be affected by this.
> 
> We are not authenticating for `in-cluster` but the method is good for environment detection.

Good point, I'll update the PR with the additional check. I was looking for something similar in the docs, but couldn't find it 🙂

**Review by climba03003 — APPROVED** [review]

**Pull request merged**
