### PR TITLE
Fix: wrong parameter with yargs-parser

### PR DESCRIPTION
**Pull request by NemoAlex**
#127

### CODE REVIEW

**Comment by cemremengu** [comment]
Do you think you can add a unit test for `parsedArgs` function ?

**Comment by NemoAlex** [comment]
@cemremengu Sorry, recently I don't have time to do that.

**Comment by cemremengu** [comment]
@NemoAlex sure no problem

**Comment by cemremengu** [comment]
@mcollina I will add tests before patching this

**Comment by cemremengu** [comment]
@NemoAlex was this really the solution to your problem? I can't seem to reproduce it. number or integer both works fine for me.

**Pull request merged**
