### PR TITLE
chore(deps): bump tap from 14 to 15.0.9

### LINKED ISSUE #368: 86 high severity vulnerabilities after init a fastify empty project
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

14.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3.1

### Description

npm found 86 high severity vulnerabilities after `npm install` for a new fastify project created with `npm init fastify`. All those vulnerabilities are from `tap` dependency.

`npm audit fix` doesn't solve those vulnerabilities.

### Steps to Reproduce

1. On a new directory run: `npm init fastify`
2. After fastify-cli creates the project run: `npm install`

### Expected Behavior

I expect a new fastify project without vulnerabilities

### PR DESCRIPTION
**Pull request by rodmoreno**
Fixes #368

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
Can you also fix all the tap deprecations?

https://gist.github.com/mcollina/e799ebb3fa9260abbe8ea56a8434ef24 might help.

**Comment by rodmoreno** [comment]
> Can you also fix all the tap deprecations?
> 
> https://gist.github.com/mcollina/e799ebb3fa9260abbe8ea56a8434ef24 might help.

Sure! I appreciate your gist!

**Comment by mcollina** [comment]
It seems the tests are failing on Windows. I think we should be running them with parallelism 1.

**Comment by rodmoreno** [comment]
Hey @mcollina according to tap docs: https://node-tap.org/docs/api/parallel-tests/ to run the tests with parallelism just require add `jobs` flag, but actually `taprc` already contains: `jobs: 1`. In theory this is enough to run them with parallelism.

I look more in deep the failing test, and I found this from tap changelog for tap 15:
> Run fixture cleanup aysnchronously on t.teardown() to minimize Windows folder locking issues.

And searching into failing test I found the following code:

```js
t.teardown(() => {
    fastifyEmitter.emit('close')
    process.chdir(cwd)
  })
  ```
  
  So probably this is causing Windows failing test I'll try to update the PR with an update to await the emit and chdir, this could fix errors on Windows.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
CI keep failing on master.

**Comment by climba03003** [comment]
Windows issue is not fixed before it is merged. 
It have a green tick because `security/snyk` always run but `github actions` need explicitly click to run.
We need to be careful whether the green CI is `security/snyk` only or having `github actions`.

**Comment by zekth** [comment]
> Windows issue is not fixed before it is merged.
> It have a green tick because `security/snyk` always run but `github actions` need explicitly click to run.
> We need to be careful whether the green CI is `security/snyk` only or having `github actions`.

This is because of the branch protection. We can ensure which action needs to be green.

**Pull request merged**
