### PR TITLE
Move fastify from devDependency to dependency.

### PR DESCRIPTION
**Pull request by coreyfarrell**
This causes fastify to be installed as a dependency of fastify-cli, as
fastify will no longer provide a command-line utility.

See fastify/fastify#514 for discussion.

### CODE REVIEW

**Comment by mcollina** [comment]
I think we should verify which version of fastify the plugin is depending on, if any.
It should match with the version the CLI is using, and also check which version is available on npm.

**Comment by coreyfarrell** [comment]
Sorry I don't understand your comment.  What plugin?

**Comment by mcollina** [comment]
With fastify-cli, you can:

fastify myapp.js

myapp.js has a package.json file, and it might have a fastify dependency. the local version should match the one used in the cli, e.g. they should be in sync, or we should show a warning. As an example, gulp does the same.

**Comment by coreyfarrell** [comment]
My new patch causes cli.js to import the best copy of fastify.  If possible we use the copy installed with myapp.js but fastify-cli bundles a copy as a fallback.

**Pull request merged**
