### PR TITLE
fix: require doesn't work in esm projects

### PR DESCRIPTION
**Pull request by mhamann**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Fixes https://github.com/fastify/fastify-cli/issues/678

### CODE REVIEW

**Comment by mhamann** [comment]
@mcollina Apologies for the delay. Unit test added. I confirmed that the added test fails with the previous code.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mhamann** [comment]
Thanks @mcollina! When do you think this might make it into a release?

**Comment by mcollina** [comment]
shipped yesterda

**Pull request merged**
