### PR TITLE
Add default readme for generated project

### LINKED ISSUE #362: Add default readme for generated project
When new project is generated it would be great if you could add a default readme that it was generated by fatisfy-cli

### PR DESCRIPTION
**Pull request by khattakdev**
Closes #362 

This PR took me a whole day to debug. There is something wrong with tests, maybe with a specific npm package.
When adding a `README.md` template in `app` and `app-ts` like following
```
# Getting Started with Fastify-CLI

This project was bootstrapped with [Fastify-CLI](https://github.com/fastify/fastify-cli).

```

This results in the failure of test suitss. A workaround for this is to add content like the following:
```
# Getting Started with Fastify-CLI

###### This project was bootstrapped with [Fastify-CLI](https://github.com/fastify/fastify-cli).
```
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
The changes looks good but the tests should be fixed

**Comment by khattakdev** [comment]
> The changes looks good but the tests should be fixed

This is quite strange. While making this PR, I tested it and it was working fine. Now I realized, it works on fine on windows machine but fails on Unix (tried on WSL2)
**Windows:**
image
**WSL2:**
image

I've been working on this since yesterday but couldn't find out what's the exact issue. Any help would be really appreciated.

**Comment by khattakdev** [comment]
With the new commit, this should work fine now. It was failing in `package.json` (description file). I didn't know it auto copy the first paragraph from `README` and add it to `description`

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]

**Pull request merged**
