### PR TITLE
fix: use dot notation

### PR DESCRIPTION
**Pull request by is2ei**
Fixed lint error.

```
$ npm run lint

> fastify-cli@5.7.1 lint
> standard

standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/is2ei/src/github.com/is2ei/fastify-cli/test/generate-esm.test.js:36:36: ["c8"] is better written in dot notation. (dot-notation)
  /Users/is2ei/src/github.com/is2ei/fastify-cli/test/generate-esm.test.js:36:67: ["c8"] is better written in dot notation. (dot-notation)
```

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by is2ei** [comment]
The test has been failed since previous commits.
https://github.com/fastify/fastify-cli/actions/runs/5323279586/jobs/9649431388?pr=634

This PR focuses on fixing the lint error.

**Comment by is2ei** [comment]
Could anyone review this?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
CI is failing :(

**Comment by is2ei** [comment]
@mcollina 

Thanks for your comment! The lint and test fail in master branch.
This PR focuses on fixing the lint error.

**Pull request merged**
