### PR TITLE
Removal of check that plugin functions need to have 3 arguments

### PR DESCRIPTION
**Pull request by piranna**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by piranna** [comment]
Fixes #199... although seems the change was already done in `master` in the last days? :thinking:

**Comment by mcollina** [comment]
CI is failing.

**Comment by piranna** [comment]
> CI is failing.

Now it's passing. Seems there was something funny with the merge.

**Comment by Eomm** [comment]
@piranna there is something strange because in the diff there are only 3 test removed

Could you check it?

**Comment by piranna** [comment]
> @piranna there is something strange because in the diff there are only 3 test removed
> 
> Could you check it?

What the...? Don't know what's happening, the code was deleted at https://github.com/fastify/fastify-cli/pull/201/commits/6e0883e7e4017c3ffe4c59eeb08b1c37ce5a3b73, and if fact it's not in my laptop clone.

**Comment by piranna** [comment]
Ok, mistery solved, the code I removed was already moved to `util.js` file, now it's fixed.

**Comment by piranna** [comment]
Thank you! :-)

**Pull request merged**
