### PR TITLE
Fix TS compilation error and add compilation to testing step

### PR DESCRIPTION
**Pull request by kibertoad**
ref #303

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by kibertoad** [comment]
@alemagio @mcollina This resolves the problem of project not compiling. Still need to add test for app failing on startup, but I believe that to be a separate issue.

**Comment by alemagio** [comment]
@kibertoad 
I created a [repo](https://github.com/alemagio/fastify-cli-ts-issue) with the same (hopefully) conditions I have.

**Comment by kibertoad** [comment]
superseded by #306

**Comment by kibertoad** [comment]
@alemagio Check #306, I tried to reproduce the issue in a test, but app starts just fine.
What do I do in `https://github.com/alemagio/fastify-cli-ts-issue`? just `npm run start`?

**Comment by alemagio** [comment]
> @alemagio Check #306, I tried to reproduce the issue in a test, but app starts just fine.
> What do I do in `https://github.com/alemagio/fastify-cli-ts-issue`? just `npm run start`?

I have issues with both `npm run start` and `npm run dev`, same problem.

**Comment by kibertoad** [comment]
@alemagio Yeah, failing locally for me as well. Considering that direction invocation of `app.ts` works, I suspect problem is with start.js being incompatible with app.ts somehow. I'll look deeper into it.

**Comment by alemagio** [comment]
Using the very same command but without fastify autoload works as shown [here](https://github.com/fastify/fastify-cli/pull/304#issuecomment-749608855) so I don't think the issue is in start.js.
Don't you think?

**Comment by kibertoad** [comment]
@alemagio But using exact same code that calls auto-load from `test/templates/app-ts.test.ts`, bypassing start.js, works, so situation is kinda muddy :). So it seems like a combination of the two, and problem could be on either, or both, sides.

**Pull request closed without merging**
