### PR TITLE
feat: add support for typescript and esm generation (#577)

### PR DESCRIPTION
**Pull request by S-Abhishek**
This PR adds support to generate Typescript ESM template.

(The implementation is currently work in progress. I will inform the thread once it's ready for a review.)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by S-Abhishek** [comment]
Hey,

Apologies for delaying this PR, couldn't find time to do it. I can now pick this up and try and complete this within 1-2 weeks based on my free time.

Thanks!

**Comment by mcollina** [comment]
Good work!

**Comment by S-Abhishek** [comment]
Hey team, does anyone have bandwidth to review this?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Thanks!

**Pull request merged**
