### PR TITLE
keep dotenv at top in order for watch env variable to be parsed before start

### PR DESCRIPTION
**Pull request by mariusa**
https://github.com/fastify/fastify-cli/issues/327

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
@simoneb you changed this in https://github.com/fastify/fastify-cli/pull/300. Wdyt of this change?

**Comment by simoneb** [comment]
I'll need to have a better look because I don't understand why the test I added in that PR is not failing with this change which basically reverts that.

**Comment by simoneb** [comment]
@mariusa can you please add a test so we avoid this regression once again? Unfortunately I think moving it back to the top breaks what was implemented in #300 , despite the test not catching it, so I don't think moving is good enough. We may actually need to have both, even though testing those cases is not straightforward.

**Comment by mariusa** [comment]
Sorry Simone, I just got started with fastify, I won't be able to make a test. Also, I had to make twice this trivial PR. First time I used vscode with my auto-formatting settings, realized only when opening the PR. I had to edit it again with a plain text editor. 

> We may actually need to have both

I've added it back too, that makes sense.

**Comment by simoneb** [comment]
See https://github.com/fastify/fastify-cli/pull/329. The change is not obvious in order to support what I introduced in #300 and to undo the regression. Longer explanation in there. I couldn't write an automated test because getting this right is not straightforward.

**Pull request closed without merging**
