### PR TITLE
Add TS Node environment variable

### PR DESCRIPTION
**Pull request by francisdaigle**
`TS_NODE_FILES` set `true` so as to load `include` on startup.

#354 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
I do not know if it is a good practice to enable this behavior by default. But it seems that if we use `fastify-autoload` with typescript, it can resolve a lot of problem.
WDYT @fastify/typescript

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by francisdaigle** [comment]
Apologies -- not a cross-platform solution.

May I update this PR @mcollina?

**Comment by climba03003** [comment]
> 
> 
> Apologies -- not a cross-platform solution.
> 
> May I update this PR @mcollina?

You can update it any time before it merge and re-request for review.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — CHANGES_REQUESTED** [review]
You need to add cross-env to the devDependencies in the generated package.json.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Can you please rebase it on top of master?

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
