### PR TITLE
fix generate plugin

### LINKED ISSUE #690: Generate plugin nitpicks to work out of the box
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x

### Plugin version

_No response_

### Node.js version

20.10.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

14.2.1

### Description

I tried to generate a fastify plugin use the CLI but encountered few small issues.
The goal is to provide a list of problems and quick solutions to make it work smoothly.

### Steps to Reproduce

Generate a new plugin using the following steps
```bash
npm install --global fastify-cli
mkdir fastify-plugin-example && cd fastify-plugin-example
fastify generate-plugin .
```
### 1. Missing `tap` module
Run unit tests, failing for missing tap module
```bash
npm run unit
```
Screenshot 2024-01-02 at 12 04 22

### 2. Tap 18.x not working with current .taprc
```bash
// Using tap 18+
npm install tap
npm run unit
```
Screenshot 2024-01-02 at 13 26 14

### 3. fastify-tsconfig throw error 
Extending the `fastify-tsconfig` inside the tsconfig.json makes the project throw.
```bash
npm run unit
```
Screenshot 2024-01-02 at 14 26 10

### 4. Missing `fastify` and `fastify-plugin` dependencies
```bash
npm run unit
```
Screenshot 2024-01-02 at 14 29 05

### 5. plugin is async while placeholder test is not waiting the registration
This could mislead the user making tests to randomly failing if the registration does not complete before the app readiness.
### Expected Behavior

To me, the example plugin should pass the tests smoothly to provide a good user experience.

### PR DESCRIPTION
**Pull request by big-kahuna-burger**
Closes #690 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by big-kahuna-burger** [comment]
Not sure why using runner gives this flaky behaviour...

**Comment by mcollina** [comment]
Does the plugin generator use node:test?

**Comment by big-kahuna-burger** [comment]
> Does the plugin generator use node:test?

Yes. [Check here](https://github.com/fastify/fastify-cli/blob/master/templates/plugin/test/index.test.js#L3)

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by big-kahuna-burger** [comment]
Merge and patch release?

**Pull request merged**
