### PR TITLE
Fix boolean env variables override

### PR DESCRIPTION
**Pull request by JGiola**
Swapped minimist with yargs-parser because works better with prefixed env variables and is currently maintained.

This move will fix issue #110.

### CODE REVIEW

**Comment by cemremengu** [comment]
How about using [meow](https://github.com/sindresorhus/meow) ?

**Comment by JGiola** [comment]
I'am sure it will work because it has the yargs-parser as a dependency. I've selected because it's used in [yargs, that is the library indicated by the developer of optimist as its successor, and is the parser used by the nyc and angular-cli project.

**Comment by cemremengu** [comment]
@JGiola fair enough, thanks for the info!

**Comment by cemremengu** [comment]
@delvedor ping

**Pull request merged**
