### PR TITLE
Enhance generated VS Code configuration

### PR DESCRIPTION
**Pull request by segevfiner**
Enhanced the generated VS Code configuration for a cleaner experience. Also simplified the `dev` command for the TypeScript template and removed `nodemon`. (P.S. Do we need `ts-node`?)

There is also the `node-terminal` launch configuration type for `launch.json`, but I'm not sure what is the difference in it in contrast to `node`. `pwa-node` is just a leftover from the debugger rewrite from a while back, and `node` is now the same thing.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm, code looks good!

@fastify/typescript could you take a look?

**Comment by segevfiner** [comment]
Heard of it, but haven't tried it. There are many ways of transpiling TS, so it can get quite opinionated. So what option we use by default should be carefully evaluated, and we might want multiple options.

**Comment by fox1t** [comment]
@segevfiner, I agree 100% with you. We can go with tsc knowing it is slow and generally is not used in the wild, and we might open a new PR in the future to let the user pick the compiler.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
