### PR TITLE
feat: lint option for typescript (blocked)

### PR DESCRIPTION
**Pull request by Mazuh**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] merge first: https://github.com/fastify/fastify-cli/pull/505
- [ ] unblocking: https://github.com/standard/ts-standard/issues/222

### CODE REVIEW

**Review by Eomm — APPROVED** [review]

**Comment by mcollina** [comment]
There are conflicts now.

**Comment by Mazuh** [comment]
sadly, tests will pass but users will still see an error in the blocking issue that I attached in the description, it's a third party blocker... so I'll mark as draft just to be safe that nobody will merge even if I fix the conflicts.

I'll see if I can do something about the error before going back to this.

**Comment by mcollina** [comment]
What's the status of this?

**Comment by Mazuh** [comment]
@mcollina I'm engaging in the discussion (https://github.com/standard/ts-standard/issues/222), but right now **I'm already open to workarounds** (like using another linter simple as the `standard` for TS).

**Comment by Divlo** [comment]
> @mcollina I'm engaging in the discussion ([standard/ts-standard#222](https://github.com/standard/ts-standard/issues/222)), but right now **I'm already open to workarounds** (like using another linter simple as the `standard` for TS).

@Mazuh As a contributor/maintainer of `ts-standard`, I recommend switching to ESLint (using https://github.com/standard/eslint-config-standard-with-typescript).
There is no energy and willpower for updating ESLint to v8 in `ts-standard` currently, no one on the team. :sweat_smile:
But if anyone wants to help `ts-standard` to move things forward, and be simpler than ESLint (like `standard` for JavaScript), they  can take a look at this: https://github.com/standard/ts-standard/issues/222#issuecomment-1054644477
Basically, a rewrite of `ts-standard`, we accept PRs and will be happy to review them.

**Comment by voxpelli** [comment]
Would be happy to work closer with the Fastify community on Standard related matters.

As a co-maintainer of Standard, a user of Fastify myself and a freelancer with lot of power over my own time I could try to help out where there is a need.

**Comment by climba03003** [comment]
> As a contributor/maintainer of ts-standard, I recommend switching to ESLint

I am agreed on using the combination of `ESLint` and `eslint-config-standard-with-typescript`. Although both `ts-standard` and `eslint-config-standard-with-typescript` is barely maintain. But `eslint-config-standard-with-typescript` recently upgraded and released for `ESLint@8`.

I don't know how long will it take for `ts-standard` and a accept the workaround for using `ESLint` with `plugin`.

> Basically, a rewrite of ts-standard, we accept PRs and will be happy to review them.

I will see if I can give a hand on it. Is there any working progress started?
Really love to see the dependencies narrow to a single one when it happen.

**Comment by Mazuh** [comment]
I'll take a look on what needs to be done here this weekend (I was super busy with something else in the last days, sorry). Gotta fix these conflicts and take a position on the next steps.

**Comment by simoneb** [comment]
I think we can close this PR, I don't think it will receive any more activity

**Pull request closed without merging**
