### PR TITLE
feat: support exporting server options using `--options` on ESM

### LINKED ISSUE #411: Support ESM for exporting server `--options`
It would be great if ESM projects could `export const options` when using the `--options` flag.

Like this:

```js
export default async (fastify, opts) => {
  // ...
}

export const options = {
  maxParamLength: 200,
}
```

For now, this seems to work:

```js
async function server(fastify, opts) {
  // ...
}

server.options = {
  maxParamLength: 200,
}

export default server
```

Not the end of the world, but I did spin my wheels for a bit thinking `export const options` would just work, since ESM is supported otherwise.

### PR DESCRIPTION
**Pull request by nooreldeensalah**
This PR resolves #411
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nooreldeensalah** [comment]
I still haven't added unit-tests, I'll see what would be the best way to test for these functionality then work on the tests, until now, I'll mark the PR as a draft

**Comment by nooreldeensalah** [comment]
I've added tests, and updated the documentation

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by nooreldeensalah** [comment]
I wanted to point out that I found a broken link in the routes' documentation in the generated `app` template, specifically here:

https://github.com/fastify/fastify-cli/blob/dd476a793a637da367d278a5041395ef1b909949/templates/app/routes/README.md?plain=1#L26-L27

Where the link should be https://www.fastify.io/docs/latest/Reference/Routes/#promise-resolution (`/Reference`) is missing

Would you like to fix this in a separate PR? Or should I make a commit fixing it here?

**Comment by mcollina** [comment]
> Would you like to have this fixed in a separate PR? Or should I make a commit fixing it here?

A fresh PR would be awesome, I'm shipping this now.

**Pull request merged**
