### PR TITLE
fix: better skip logic

### PR DESCRIPTION
**Pull request by big-kahuna-burger**
This adds better logic for skipping certain tests that rely on `--no-coverage` flag to be provided.
Ideally, all test suites I should be able to run with any of:
- `tap /pattern/`
- `tap /pattern/ --no-coverage`
- `c8 tap /pattern/`

This PR gives me that flexibility for these 2 suites (`test/print-*.test.js`)

BEFORE:
```sh
tap test/print-*.test.js
=>
...
Suites:   ​1 failed​, ​1 passed​, ​2 of 2 completed
Asserts:  ​​​3 failed​, ​25 passed​, ​of 28

c8 tap test/print-*.test.js
=>
... 
Suites:   ​1 failed​, ​1 passed​, ​2 of 2 completed
Asserts:  ​​​3 failed​, ​25 passed​, ​of 28

tap test/print-*.test.js --no-coverage
=> 
...
Suites:   ​2 passed​, ​2 of 2 completed
Asserts:  ​​​28 passed​, ​of 28
```

NOW:

```sh
tap test/print-*.test.js
=> 
...
Suites:   ​2 passed​, ​2 of 2 completed
Asserts:  ​​​20 passed​, ​4 skip​, ​of 24

c8 tap test/print-*.test.js
=> 
...
Suites:   ​2 passed​, ​2 of 2 completed
Asserts:  ​​​20 passed​, ​4 skip​, ​of 24

tap test/print-*.test.js --no-coverage
=> 
...
Suites:   ​2 passed​, ​2 of 2 completed
Asserts:  ​​​28 passed​, ​of 28
```

Clarification:
- `tap` (16.x) without a `--no-coverage` flag will have a `NYC_PROCESS_ID` in `process.env`
- `c8` [will assign](https://github.com/bcoe/c8/blob/a13584d5be5259ebb6a00455d352c3e8b16006de/bin/c8.js#L36C1-L36C1) a coverage/tmp dir into a  `NODE_V8_COVERAGE` env variable

CI was not the reason those tests hanged.
It is `c8` in `test` script that is being run by CI, on top of all unit tests with `--no-coverage` flag, resulting in effectively undo-ing what that flag was doing for local testing anyway.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by big-kahuna-burger** [comment]
@mcollina PTAL

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by big-kahuna-burger** [comment]
What is the reason for remaining broken test?
I'm confused as to where `tap` should be looking for `fastify-tsconfig` with that setup?

(it's broken locally as well)

**Comment by big-kahuna-burger** [comment]
So, those `fastify-tsconfig` searches errored because of how tsconfig's resolution algorithm works.

Very simple fix is to not point to templates/**/tsconfig.json, and try to resolve fastify-config from there, but to point to a copy of it which I've put in `test/configs` that has direct resolution to a file in node_modules.

For even more clarity, I've refactored pkg.scripts that deal with tests into the following shape:

```
test/
├─ unit:cli/
│  ├─ unit:cli-js
│  ├─ unit:cli-ts
├─ unit:templates/
│  ├─ unit:cjs
│  ├─ unit:esm
│  ├─ unit:ts-cjs
│  ├─ unit:ts-esm
├─ test:typescript/
│  ├─ tsd
│  ├─ tsc
```

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by big-kahuna-burger** [comment]
@mcollina you can just re-run this failed test. 
Happened to hang sometimes in my action as well, likely a timeout issue rather than code correctness issue. Tested locally with node 21 and it's passing.

**Comment by big-kahuna-burger** [comment]
Looking good now

**Pull request merged**
