### PR TITLE
Remove build:ts step from npm start Task

### PR DESCRIPTION
**Pull request by zoulou00**
[

#### Checklist

- [x] run `npm run test` 
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)
](https://github.com/fastify/fastify-cli/issues/705)

### CODE REVIEW

**Comment by mcollina** [comment]
Why?

**Comment by zoulou00** [comment]
To resolve the issue https://github.com/fastify/fastify-cli/issues/705

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for the context.
I think we should have:

1. `npm start` that starts the server for production
2. `npm start:dev` that calls `npm run build:ts` and `npm start`

**Comment by bishopandco** [comment]
I stumbled on this PR because I am doing DevOps for a fastify app (that I didn't write) and was looking for recommendations for running fastify in supervisor.conf.

**Comment by jean-michelet** [comment]
I think this PR can be closed now: https://github.com/fastify/fastify-cli/blob/64889056801046b3d4ebce218ad119a88b4b1631/generate.js#L55

**Pull request closed without merging**
